### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by dlfjr1** [tonywagner/EPlusTV#101]
I installed and got authorized by ESPN.  When I try to go to the docker url, it says 404 Not Found.  I put in 192.168.1.41:8000
What am I doing wrong?

**Comment by m0ngr31** [comment]
You can't use it on its own. You have to ingest the schedule into some type of DVR application and play from there

**Comment by J91-cloud** [comment]
I am getting the same issue 404 not found and when i try to add a DLR in plex it will not work

**Comment by m0ngr31** [comment]
What URLs are you adding to Plex?

**Comment by m0ngr31** [comment]
Closing stale ticket
