### ISSUE TITLE
mlb not working, new mlb.tv api?

### ISSUE THREAD

**Issue by SethL** [tonywagner/EPlusTV#102]
I think mlb is using a new api as EplusTV wont play any mlb stream as of today.  I found this over here for mlbserver if that helps:
https://github.com/tonywagner/mlbserver/issues/44 

    statusText: 'Unauthorized',
    headers: AxiosHeaders {
      'content-type': 'application/json; charset=utf-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      date: 'Fri, 19 Jul 2024 23:12:05 GMT',
      'x-dss-edge': 'auth.bad-partner',
      'www-authenticate': 'Bearer code="access-token.invalid", description="auth.bad-partner"',
      'x-request-id': '6d7bbbd6c1396bc61ae094eae07b4ed2',
      'x-bamtech-region': 'us-east-1',
      'cache-control': 'no-store',
      'x-cache': 'Error from cloudfront',

**Comment by Timbo303** [comment]
This is the same issue I have too. Mlb.tv Kodi addon just recently fixed this issue but not eplustv yet.

**Comment by m0ngr31** [comment]
Should be fixed in v2.1.13 - that being said you have to delete your `entries.db` and `schedule.db` files before running the update
