### ISSUE TITLE
Golazo Network Paramount+

### ISSUE THREAD

**Issue by 3eesa54** [tonywagner/EPlusTV#103]
Can you add the Golazo Network on Paramount+ to the list of items that gets imported?  It is a 24/7 streaming channel that shows football games on it as well.

**Comment by m0ngr31** [comment]
I'll investigate this. I did see it when I was adding the Paramount+ stuff, but it's tricky with the way the scheduling works to have a 24/7 event. I'll have to see how it'd work

**Comment by m0ngr31** [comment]
I've added support for this in v3.0.0. You'll have to enable `LINEAR_CHANNELS` and use the separate xmltv and m3u endpoints to access it
