### ISSUE TITLE
[Request] Add Flosports if possible

### ISSUE THREAD

**Issue by jmvbrown** [tonywagner/EPlusTV#104]
Would it be possible to add flosports?

**Comment by m0ngr31** [comment]
It's possible if they don't use DRM in their streams. I'd need an account. It seems like they have different levels of accounts or different services that you can subscribe to. So it might be tricky to try all of that out. I'd probably need multiple logins to test the different scenarios

**Comment by jmvbrown** [comment]
I believe it is all the same subscription, but they break up the website into FloFootball, FloBasketball, etc

**Comment by m0ngr31** [comment]
Oh I thought they had different subs for each or one that had them all

**Comment by m0ngr31** [comment]
@jmvbrown are you willing to email me your Flosports credentials so I can try adding it?

**Comment by jmvbrown** [comment]
I’d be willing to!

**Comment by m0ngr31** [comment]
@jmvbrown You can find my email on my Github profile page. Thanks

**Comment by m0ngr31** [comment]
Added in 2.3.0
