### ISSUE TITLE
[Feature] NFL+

### ISSUE THREAD

**Issue by mdo77** [tonywagner/EPlusTV#107]
As we approach NFL season, I was wondering if you've ever explored support for NFL+.  It has a lot of on-demand stuff which I'm less interested in, but it does have linear channels for NFL Network on the base package as well as NFL Red Zone on the premium package.

![image](https://github.com/user-attachments/assets/457a583a-60bc-4b85-9b16-6ca306c266b9)

**Comment by m0ngr31** [comment]
Do you know if they are using DRM?

**Comment by mdo77** [comment]
I'd be happy to investigate, but I'm not quite sure how to tell. If I bring
up a stream, what should I look for? (I'm a web developer by trade and have
lots of experience in the Chrome developer tools if the answers are there).

**Comment by m0ngr31** [comment]
Yeah, open the network inspector in Chrome while you're playing NFL Network (for example), and look at the XHR traffic. You want to look for the `*.m3u8` files. We need to see if they say anything about keys or if you see any traffic referencing Widevine, Fairplay, ect.

**Comment by mdo77** [comment]
Not seeing anything obviously referencing those keywords, at least.

![image](https://github.com/user-attachments/assets/adacdbfe-fb0c-475a-b8e6-3ba2456dc3ab)
![image](https://github.com/user-attachments/assets/f2bccecd-9731-4c80-bd5b-7e2d5f7508c4)

**Comment by m0ngr31** [comment]
@mdo77 are you willing to email me your credentials so that I can try this out?

**Comment by mdo77** [comment]
Why don't I just venmo you $15 to get a month and see what you can do.

**Comment by mdo77** [comment]
> @mdo77 are you willing to email me your credentials so that I can try this out?

Actually I just got a code for a free month of the service from DraftKings. I forwarded to the email you  have on your github profile.

**Comment by m0ngr31** [comment]
Thanks, that is great!

**Comment by m0ngr31** [comment]
Okay, pushed out a new version (v3.0.0) tonight that supports NFL+
