### ISSUE TITLE
Add New England Sports Network (NESN)

### ISSUE THREAD

**Issue by cbahern** [tonywagner/EPlusTV#109]
Can you add New England Sports Network (NESN)?  Link to watch is https://nesn.com/watch/

There is a seperate app option NESN360 if that helps. 

I am willing to provide login session information if you point me in the right direction for capturing (tools, etc.)

**Comment by m0ngr31** [comment]
The issue is that when I'm developing it I have to see how the entire login flow works (and refreshing tokens, ect.), so I really need credentials to capture the entire process. If you're willing to lend me your login I'll see if I can add it

**Comment by cbahern** [comment]
Joe,

Login details:

***@***.***:0ne0rzer0  (these are zeros)
Xfinity:       ahernwatch:!One0rzer0! (the second two are zeros, first is capital O)

Thanks for looking at this, and for all your efforts on this great piece of software!

Chuck
________________________________

**Comment by m0ngr31** [comment]
@cbahern I'd delete this since it's public. Shoot me an email instead: joe[@]ipson.me

**Comment by m0ngr31** [comment]
Added in v3.2.0
