### ISSUE TITLE
im able to connect to linear endpoints but they come up blank

### ISSUE THREAD

**Issue by Zespo06** [tonywagner/EPlusTV#112]
Hi all!

Im currently trying to setup linear channels so streams dont interlap and can be on their own channels in Jellyfin. Im using docer-compose. i set "LINEAR_CHANNELS=true" in environment. i know my environment variables are setup right since i change dit to 300 channels and added paramount plus. I can connect to the linear endpoints and xTeVe and it shows 100% availability, but 0 streams. When i go to the linear-xmllist.xml from a browser, only one line shows up. im not sure if im doing something wrong since im fairly new to docker. 
![image](https://github.com/user-attachments/assets/ba07a12f-d22b-472b-a1aa-ebb518dae5bb)

I can connect to both channels.m3u and linear-channels.m3u in xTeVe at the same time, with non-linear showing 300 channels and linear showing 0
![image](https://github.com/user-attachments/assets/f5b3b6b0-0c93-4dda-8156-aaa6d08298bd)

here is my docker-compose config.yaml
version: "3.3"
services:
  eplustv:
    ports:
      - 8000:8000
    volumes:
      - /opt/dockge/eplustv:/app/config
    environment:
      - NUM_OF_CHANNELS=300
      - LINEAR_CHANNELS=true
      - PARAMOUNTPLUS=true
      - MLBTV_ONLY_FREE=true
    image: m0ngr31/eplustv
networks: {}

any help would be appreciated. Thank you!

**Comment by Zespo06** [comment]
update, i added regular espn from my TV provider and it created a linear channel, so im assuming that its only for services that sign in through a cable account? is there any way to make linear channels for epsn+ and paramount plus?

**Comment by m0ngr31** [comment]
The `LINEAR_CHANNELS` option is only available for traditional TV channels. So ESPN+ events won't be scheduled that way. 

For Paramount+, you'd have to add in `CBSSPORTSHQ` or `GOLAZO` to get those channels. Hopefully that makes some kind of sense?

**Comment by Zespo06** [comment]
Makes perfect sense, Once i wrote that update i tried CBSSPORTSHQ and another linear channel loaded. Then it clicked in my head haha. I was actually coming to close this ticket out but looks like you beat me to it :) thank you for being helpful and quick to respond!
