### ISSUE TITLE
Devils game today not appearing

### ISSUE THREAD

**Issue by adamef93** [tonywagner/EPlusTV#113]
The game appears if I log into the MSG+ site as starting with pregame at 12:30pm Eastern, but doesn't show up in the M3U generated by EPlus. I don't know if this is because the feed is being shared with NHL Network and I'm also not sure which one is getting the direct feed vs which one is simulcasting, but I would think it being available on the MSG+ website and app would be enough.

**Comment by m0ngr31** [comment]
Can you email your MSG credentials so I can look at it real quick? It's been a minute since I've done anything with that service

**Comment by adamef93** [comment]
Sent. You're the man.

**Comment by m0ngr31** [comment]
Okay, new version is going out now

**Comment by adamef93** [comment]
You absolute angel. Thank you so much!
