### ISSUE TITLE
Reverse Proxy Base URL option

### ISSUE THREAD

**Issue by voc0der** [tonywagner/EPlusTV#115]
:wave:  thanks for this project!

I'm trying to reverse proxy this so it's going through a domain instead of ip:port and the channels.m3u, etc generate with the containername:port/...

Is there any way to make it generate the channels with a custom base URL, e.g. sports.mydomain.com?

I found 3 places in the code where it appears to be referencing request headers to build the URI. Perhaps if it's available, this is what can be overridden by env var(s).

https://github.com/m0ngr31/EPlusTV/blob/f27d68f39585612c9faf81ad9fc3268dd8cf39a5/index.ts#L61
https://github.com/m0ngr31/EPlusTV/blob/f27d68f39585612c9faf81ad9fc3268dd8cf39a5/index.ts#L80
https://github.com/m0ngr31/EPlusTV/blob/f27d68f39585612c9faf81ad9fc3268dd8cf39a5/index.ts#L136

**Comment by m0ngr31** [comment]
I'll cut a release for this today
