### ISSUE TITLE
Attempting to play a stream crashes computer

### ISSUE THREAD

**Issue by jmvbrown** [tonywagner/EPlusTV#119]
When ever I play a stream, Jellyfin loads forever and then crashes the entire computer. This wasn't happening before the latest update. I've tested the steams I was trying to play in VLC and they play. When I try watching the same stream in Jellyfin, I watch the RAM in the Unraid Dashboard go towards 100%. The stream never starts and then the computer crashes.

**Comment by m0ngr31** [comment]
Did you get it figured out? The playback side of the code didn't change at all

**Comment by jmvbrown** [comment]
No I didn't, I thought I would try other things, but nothing is working. The log in EPlusTV shows the stream is being started, but in Jellyfin, it just spins like it is trying to start the stream and then the RAM continues to go up towards 100%

**Comment by m0ngr31** [comment]
I've actually never gotten it to work in Jellyfin before - but I'm getting the m3u and xmltv from Channels. I wonder if I need to try playback directly from E+ instead

**Comment by m0ngr31** [comment]
I did add some code a few weeks back (#111) to better support Emby, I wonder if that busted Jellyfin? I doubt it, but maybe if you hadn't updated since then?

**Comment by jmvbrown** [comment]
EPlusTV Log: https://pastebin.com/GxgHCccU

Jellyfin Log: https://pastebin.com/KrqFWDMH

**Comment by jmvbrown** [comment]
I'm running it in Unraid so I definitely updated since then

**Comment by jmvbrown** [comment]
It was actually working for me up until this most recent update

**Comment by jmvbrown** [comment]
It seems like the auto loop button in Live TV was the issue

**Comment by m0ngr31** [comment]
So did that fix it then?

**Comment by jmvbrown** [comment]
Yes it did
