### ISSUE TITLE
NFL channels

### ISSUE THREAD

**Issue by gzowner** [tonywagner/EPlusTV#121]
Way to get the NFL channels for the games to show up? I have all 3 providers, and Youtube but cant get the games to show.. whats missing?

docker run --security-opt apparmor=unconfined --restart unless-stopped --name EPlusTV -p 8000:8000 -v /media/espn:/app/config -e LINEAR_CHANNELS=TRUE -e NUM_OF_CHANNELS=1000 -e START_CHANNEL='1000' -e m0ngr31/eplustv

**Comment by gzowner** [comment]
![image](https://github.com/user-attachments/assets/c7256d91-ec95-45fd-8b6a-a205dd3494c4)
assuming it will show here

**Comment by m0ngr31** [comment]
Linear channels have their own m3u to import
