### ISSUE TITLE
Duplicate events in Gotham

### ISSUE THREAD

**Issue by adamef93** [tonywagner/EPlusTV#123]
Hate to keep bothering you, but wanted to see what was up with this. I'm getting 2 events for tomorrow night's Devils game. The first one is the full 3 hours starting at 8:30 with the pregame and the second is at 9:30 which would probably end up being about halfway through the second period. Oddly enough, the second one has the icon that it's queued to record, but there's no option to cancel it to prevent duplicates. I only have the option to record it despite it looking queued. The first one is queued, though.

Worst case, I end up with a duplicate, but just seems weird. It's still there after removing and re-adding the EPlus source in Channels.

![image](https://github.com/user-attachments/assets/624df979-0f9f-48cf-8f25-004115f355c7)
![image](https://github.com/user-attachments/assets/079d9a3b-40ae-4b3b-8cd3-ceccceaba38f)
![image](https://github.com/user-attachments/assets/c1d49b92-2c5b-4a71-bde4-f7eb853a55df)

Thanks again!

**Comment by m0ngr31** [comment]
Kind of a strange situation. If you look at the schedule here: https://www.msgnetworks.com/schedule/#

It looks like the Islanders game is taking priority and it has a shortened broadcast for the Devils game? I'm not sure

![image](https://github.com/user-attachments/assets/add8c2d9-276d-4ee3-9102-ac3c2b6131d6)

**Comment by adamef93** [comment]
Yup, this is totally my bad. I switched to using linear channels and now see that the one that starts later is tagged as "Joined in progress", so it's being played on both channels after the Islanders game ends. Adjusted my DVR pass to ignore that tag and only record the main one

Thanks!
