### ISSUE TITLE
VPN error

### ISSUE THREAD

**Issue by jonbbrad** [tonywagner/EPlusTV#135]
I'm trying to use ETV through a VPN container and am getting this error: 
> ts-node -r tsconfig-paths/register index.tsx

=== E+TV v4.1.3 starting ===

Error: listen EADDRINUSE: address already in use 0.0.0.0:8000

    at Server.setupListenHandle [as _listen2] (node:net:1817:16)

    at listenInCluster (node:net:1865:12)

    at doListen (node:net:2014:7)

    at processTicksAndRejections (node:internal/process/task_queues:83:21) {

  code: 'EADDRINUSE',

  errno: -98,

  syscall: 'listen',

  address: '0.0.0.0',


  port: 8000

}

I'm using Gluetun for the VPN. I have other containers going through the same VPN without issue and have port 8000 open on the VPN.

**Comment by m0ngr31** [comment]
As a matter of principle I won't support running this with a VPN since bypassing geo-restrictions is the quickest way I'll get a cease & desist warning for this. So unfortunately you're on your own
