### ISSUE TITLE
Starts for while then crashes 

### ISSUE THREAD

**Issue by justinglock40** [tonywagner/EPlusTV#15]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/23133649/154846595-dcd032c2-4219-4f91-a606-27e09b0facb0.png">

**Comment by justinglock40** [comment]
Looks like this happens when trying to mount /app/tmp to /dev/shm. When that is mounted the pwsuer can't chown and it stays as root. 

Removing that /dev/shm the container can chown.

**Comment by m0ngr31** [comment]
That's a good find thanks

**Comment by m0ngr31** [comment]
I've updated the docs to not show this as a default argument.
