### ISSUE TITLE
Lots of zombie processes being left

### ISSUE THREAD

**Issue by justinglock40** [tonywagner/EPlusTV#16]
Something in the code is leaving behind lots of zombies processes:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/23133649/155653057-03141612-726a-442e-b2ef-37bc407d79b3.png">

<img width="270" alt="image" src="https://user-images.githubusercontent.com/23133649/155653102-db3737b1-2e61-4c36-a1e3-f4b3050bd201.png">

**Comment by m0ngr31** [comment]
Hopefully this is fixed on the new version!
