### ISSUE TITLE
30 or 60 fps Streams?

### ISSUE THREAD

**Issue by rh535** [tonywagner/EPlusTV#17]
Is it possible to have the streams at a higher FPS? I am running this through unRAID and then to Tivimate and see the streams only stream at 24fps. I then play the same event through the ESPN app on my shield and it clearly seems to run smoother.

Any tips?

Thanks for your work!

**Comment by m0ngr31** [comment]
That's a good observation. I'll have to look into this. Could be an issue with getting the stream from streamlink or making a new one with ffmpeg.

**Comment by m0ngr31** [comment]
New version does 60fps by default
