### ISSUE TITLE
Failed to parse Stream on Active Event

### ISSUE THREAD

**Issue by PeebsATX** [tonywagner/EPlusTV#19]
` Server started on port 8000

 There is an active event. Going to start the stream.
 

 Getting stream for event:  9a046ce9-abe4-4319-a596-9a66e0a8d8f8
 

 Failed to parse the stream
 

 Failed to parse the stream
 
 There is an active event. Going to start the stream.
 

 Getting stream for event:  9a046ce9-abe4-4319-a596-9a66e0a8d8f8`

<img width="1275" alt="Screen Shot 2022-05-02 at 10 45 13 AM" src="https://user-images.githubusercontent.com/11236420/166268573-6f137f8b-28c4-4da7-b40b-3e75c4b26a37.png">

**Comment by m0ngr31** [comment]
Could be a few different issues:

* Game is blacked out for your location
* Event hasn't started/Event has ended

**Comment by PeebsATX** [comment]
I don't think so, I logged into my account on my browser and checked if the events were active and I could stream them, both worked fine.

**Comment by PeebsATX** [comment]
There is a error npm throws on startup not sure if it could be related. 



`33 verbose node v14.17.6
34 verbose npm  v7.24.2
35 error path /app
36 error command failed
37 error signal SIGTERM
38 error command sh -c ts-node "index.ts"
39 verbose exit 1`

**Comment by m0ngr31** [comment]
The mechanism for getting the streams has been re-written. Can you try again?
