### ISSUE TITLE
EACCESS Denied error on start

### ISSUE THREAD

**Issue by cknic** [tonywagner/EPlusTV#20]
Looking at the docker logs i'm getting an EACCESS denied error and googling it looks to be an npm error, but i can't seem to get it to work.

**Comment by flex36ty** [comment]
Im getting the same error too

**Comment by SoSJames** [comment]
If it helps, what you're seeing is a permissions issue. The /app/config directory specified in the run file needs to be accessible by whichever account you're running the docker image with. If you correct that, your issue should go away.

**Comment by m0ngr31** [comment]
Following what @SoSJames said should fix the issue
