### ISSUE TITLE
Docker permission issue

### ISSUE THREAD

**Issue by drewbitt** [tonywagner/EPlusTV#30]
Currently the docker run command does not initialize the required files for me and errors the same as #20 and #9. 

This is solved via
```
touch entries.db
touch schedule.db
echo "{}" > tokens.json
```
and a `chown nobody:users .` for me in unraid. The application then has no issue reading and writing to the files that it was complaining about permission errors on before.

**Comment by m0ngr31** [comment]
I'll see what I can do about this

**Comment by drewbitt** [comment]
New version worked for me, thanks
