### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ehosch** [tonywagner/EPlusTV#31]
Great work BTW!  Is it possible to store our ESPN credentials in a config file so that the docker image activates automatically after a restart?

**Comment by m0ngr31** [comment]
If you set a config directory it should be saving the tokens that are generated by the authentication.

**Comment by ehosch** [comment]
Here is my Docker Compose:
`  eplustv:
    image: m0ngr31/eplustv
    container_name: eplustv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - ESPN_USER=***omitted***
      - ESPN_PASS=***omitted***
      - START_CHANNEL=7000
    volumes:
      - /media/Data/EPlusTV/app/config:/app/config
      - /media/Data/EPlusTV/app/tmp:/app/tmp
    ports:
      - 8000:8000
    restart: unless-stopped`

Everytime I restart the container I get:

Please open a browser window and go to: https://www.espn.com/watch/activate
