### ISSUE TITLE
Streams freezing a jittery

### ISSUE THREAD

**Issue by Rob2k9** [tonywagner/EPlusTV#32]
streams are working but seems very jittery and freeze often anyway to improve this 

i have it on an 19 with nvidea 2060 super and 32 gb ram with a 1gbps fiber line i tested the website and it plays fine

**Comment by m0ngr31** [comment]
What OS is your host running? Can you see which processes are spiking (ffmpeg vs streamlink)?

**Comment by m0ngr31** [comment]
I'm going to consolidate to #29
