### ISSUE TITLE
[Enhancement Requests] - stream origin, filter by sport, Fox Sports integration

### ISSUE THREAD

**Issue by lionsnob** [tonywagner/EPlusTV#33]
Hello -

Thank you for this software! I have three requests:

1) Can we have an option to see the source of the stream in the title (ESPN+/ESPN3, other future ESPN streams). I notice that the ESPN3 streams don't always work and I'd like to easily identify which streams come from where.

2) Can we have a way to filter by sport? For example, I'm typically interested in college football, college basketball and college hockey.

3) Any chance to add Fox Sports digital streams to this?

I'm using this software through tvheadend and it's really neat!

**Comment by m0ngr31** [comment]
1. Yeah, I'll investigate on what I can do to differentiate the different networks (probably once I get the other networks working)
2. Are you wanting to exclude other sports completely?
3. I don't have a Fox Sports account, so I'm not sure how they handle their streams. I'd have to find someone with an account and reverse engineer it all. I'd prefer to figure out the other ESPN networks first though

**Comment by lionsnob** [comment]
Thanks! No problem on the Fox Sports stuff. 

For #2, yes I’d like to specify which sports to include and exclude the others.

**Comment by m0ngr31** [comment]
I've added in 1 and 3 so I'm going to close this for now.

Adding in 2 won't be straightforward with how the event filtering would work across ESPN/ESPN+/FOX

**Comment by lionsnob** [comment]
Thank you!

Steve
