### ISSUE TITLE
Disabling ESPNPLUS With Any Other Channel Enabled Crashes Container

### ISSUE THREAD

**Issue by thompatry** [tonywagner/EPlusTV#34]
Whenever you disable ESPNPLUS but enable other channels such as ESPN on first run, it allows you to authenticate with a TV Provider but then crashes. Nothing is in the log when it crashes. When you re-enable ESPNPLUS, it has you authenticate for ESPN+ and then it works. 

```
> eplustv@2.0.0 start
> ts-node index.ts

:: TV Provider Auth ::
Please open a browser window and go to: https://www.espn.com/watch/activate
Enter code:  xxxxxx
App will start when login has completed...

> eplustv@2.0.0 start
> ts-node index.ts
```

EDIT: I will also note, when you re-enable ESPNPLUS, you cannot watch your ESPN stream.

**Comment by m0ngr31** [comment]
I'll double check this. Thanks

**Comment by m0ngr31** [comment]
This should be fixed now
