### ISSUE TITLE
Differentiate local streams

### ISSUE THREAD

**Issue by PaulMcMillan** [tonywagner/EPlusTV#36]
Thanks for this, it has been working great so far with Channels!

I'm watching Hockey, which generally has two streams for each game (with the local team's announcers and graphics). Right now, I don't see any way to filter to my team's broadcast based on data in the xmltv file. Any chance we could parse that data while generating the listings?

**Comment by m0ngr31** [comment]
That's a great suggestion. I'll see what I can figure out!

**Comment by m0ngr31** [comment]
This should be fixed now
