### ISSUE TITLE
Streams not working

### ISSUE THREAD

**Issue by BluchipStudio** [tonywagner/EPlusTV#37]
i have eventhing installed and logged in with my account but when i got to play a stream i get the eplustv loading and nothing else 

when i check my logs i see the following

`      'x-amz-cf-id': 'oY7G920a6ypCneh-90JDzd0JO1slDRubzjks56rbTHn0rDL7hoOYuA=='
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      url: 'https://us.edge.bamgrid.com/token',
      data: 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&latitude=0&longitude=0&platform=browser&setCookie=false&subject_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyZWZkYWJiYS0zMWMxLTRmNWYtODE3Yi1kNjAwYzdiM2NhYjYiLCJhdWQiOiJ1cm46YmFtdGVjaDpzZXJ2aWNlOnRva2VuIiwibmJmIjoxNjcwMTA4MjQzLCJpc3MiOiJ1cm46YmFtdGVjaDpzZXJ2aWNlOmRldmljZSIsImV4cCI6MjUzNDEwODI0MywiaWF0IjoxNjcwMTA4MjQzLCJqdGkiOiJiOTJmZGUzZi02ZjU2LTRlZjYtOGVjNC02N2Y2Y2NlNzUyMzYifQ.NEd81x-2wYLqJBRpCJj_PFSdMrt_SRvpPDOjd5jbbUwcQ4-f6XushmsHk9AtRviv25SvarPwk2RfhidD44Ej2A&subject_token_type=urn%3Abamtech%3Aparams%3Aoauth%3Atoken-type%3Adevice'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
Could not get BAM access token
      _header: 'POST /token HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Authorization: Bearer ZXNwbiZicm93c2VyJjEuMC4w.ptUt7QxsteaRruuPmGZFaJByOoqKvDP2a5YkInHrc7c\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Content-Length: 617\r\n' +
        'Host: us.edge.bamgrid.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'us.edge.bamgrid.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: { errors: [Array] }
  }
}
TypeError: Cannot read properties of undefined (reading 'refresh_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:807:53)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'access_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:763:38)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'assertion')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:829:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by m0ngr31** [comment]
ESPN or ESPN+ event?

**Comment by BluchipStudio** [comment]
> ESPN or ESPN+ event?

it was an ESPN+ event i think it was an event from the epg that app had listed

**Comment by m0ngr31** [comment]
There isn't much I can go off of from that log... Make sure your container is on the most up to date version and the event you're trying to watch is available in a browser as well (not pre/post event, blacked out, ect)?

**Comment by BluchipStudio** [comment]
> There isn't much I can go off of from that log... Make sure your container is on the most up to date version and the event you're trying to watch is available in a browser as well (not pre/post event, blacked out, ect)?

Hi thank for the reply i have just done a check and got the following

i check the event :  U Mumba vs. Dabang Delhi KC it is currently live and mapped to : 1.eplustv

i checked on the espn+ website and the event worked no problem 
![Untitled](https://user-images.githubusercontent.com/103538584/205950467-8a517460-8582-4f17-ba03-e28440cadee9.png)

when i play the stream i get the starting soo screen then it just tries to load and gets stuck when i check the logs i get the following 

`      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      url: 'https://us.edge.bamgrid.com/token',
      data: 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&latitude=0&longitude=0&platform=browser&setCookie=false&subject_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyZWZkYWJiYS0zMWMxLTRmNWYtODE3Yi1kNjAwYzdiM2NhYjYiLCJhdWQiOiJ1cm46YmFtdGVjaDpzZXJ2aWNlOnRva2VuIiwibmJmIjoxNjcwMTA4MjQzLCJpc3MiOiJ1cm46YmFtdGVjaDpzZXJ2aWNlOmRldmljZSIsImV4cCI6MjUzNDEwODI0MywiaWF0IjoxNjcwMTA4MjQzLCJqdGkiOiJiOTJmZGUzZi02ZjU2LTRlZjYtOGVjNC02N2Y2Y2NlNzUyMzYifQ.NEd81x-2wYLqJBRpCJj_PFSdMrt_SRvpPDOjd5jbbUwcQ4-f6XushmsHk9AtRviv25SvarPwk2RfhidD44Ej2A&subject_token_type=urn%3Abamtech%3Aparams%3Aoauth%3Atoken-type%3Adevice'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /token HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Authorization: Bearer ZXNwbiZicm93c2VyJjEuMC4w.ptUt7QxsteaRruuPmGZFaJByOoqKvDP2a5YkInHrc7c\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Content-Length: 617\r\n' +
        'Host: us.edge.bamgrid.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'us.edge.bamgrid.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      error: 'unauthorized_client',
      error_description: 'forbidden-location'
    }
  }
}
TypeError: Cannot read properties of undefined (reading 'refresh_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:807:53)
Could not get BAM access token
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'access_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:763:38)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'assertion')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:829:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Cleaning up old events
=== Done getting events ===
=== Building the schedule ===
=== Done building the schedule ===
Channel has upcoming event. Setting timer to start`

is there a way to view more detailed logs ?

**Comment by m0ngr31** [comment]
Can you use pastebin or something to dump your full log? I can't see what HTTP error you're getting

**Comment by m0ngr31** [comment]
As a test, nuke your config folder and try authenticating again

**Comment by BluchipStudio** [comment]
> As a test, nuke your config folder and try authenticating again

hi thanks for the reply sorry its been so slow xmas period with three kids tobuy for is hell 

i will give reauthing a try today and let you know

**Comment by m0ngr31** [comment]
I'm going to close this out for now since the entire playback engine has been changed out.
