### ISSUE TITLE
ESPN = 24fps Streams

### ISSUE THREAD

**Issue by rh535** [tonywagner/EPlusTV#39]
I keep getting 24FPS streams with ESPN. This was an issue before that seems to have come back

**Comment by m0ngr31** [comment]
ESPN or ESPN+?

**Comment by rh535** [comment]
> ESPN or ESPN+?

It seems to be both for me (what shows up in Tivimate)

**Comment by m0ngr31** [comment]
I've just double checked on the latest release that events are playing at 60fps. There are some events that don't have 60fps, so maybe that is the issue?

**Comment by rh535** [comment]
I tried various events on ESPN, ESPN+ and FSP all said 24 fps in Tivimate.

> I've just double checked on the latest release that events are playing at 60fps. There are some events that don't have 60fps, so maybe that is the issue?

**Comment by m0ngr31** [comment]
Can you try opening one of the streams in VLC? Then we can figure out if it's a bug in Tivimate

Also can you paste in your docker run command?

**Comment by rh535** [comment]
> Can you try opening one of the streams in VLC? Then we can figure out if it's a bug in Tivimate
> 
> Also can you paste in your docker run command?

I wonder if this is a Tivimate issue????

VLC:
Channel 1 for me as -  Frame rate = 59.940060 (ESPN+ hockey game)


**Here is my  docker run command:**

`docker run
  -d
  --name='EPlusTV'
  --net='proxynet'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="EPlusTV"
  -e 'ACCESS_URI'='192.168.1.11'
  -e 'START_CHANNEL'=''
  -e 'ESPNPLUS'='true'
  -e 'ESPN'='true'
  -e 'ESPN2'='true'
  -e 'ESPN3'='true'
  -e 'ESPNU'='true'
  -e 'SEC'='true'
  -e 'SECPLUS'='true'
  -e 'FOXSPORTS'='true'
  -e 'FOXSPORTS_ALLOW_REPLAYS'='false'
  -e 'STREAM_RESOLUTION'='720p60'
  -e 'FOXSPORTS_MAX_RESOLUTION'='UHD/HDR'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://i.imgur.com/LrdVje2.png'
  -p '8836:8000/tcp'
  -v '/mnt/user/appdata/eplustv':'/app/config':'rw'
  -v '/mnt/user/tmp/':'/app/tmp':'rw'
  --ipc=host 'm0ngr31/eplustv'
fc79940e86938982b967697ed847dcc451ff671054ff602e643fa7eca65ecccb

The command finished successfully!

`

**Comment by m0ngr31** [comment]
Yesh that's my guess. I'm wondering if it's reporting the wrong framerate or it's actually playing at a lower one...

I'm wondering if it's grabbing and reporting the framerate of the slate that plays before the event starts playing. I think that's 24fps

**Comment by rh535** [comment]
> Yesh that's my guess. I'm wondering if it's reporting the wrong framerate or it's actually playing at a lower one...
> 
> I'm wondering if it's grabbing and reporting the framerate of the slate that plays before the event starts playing. I think that's 24fps

I played Greeny (ESPN+) in ImPlayer and it shows 0FPS - which it definitely isn't. Just passing along some info.

Thanks for all your work. Adding Fox Sports is awesome. Thanks again for the help and the app.

**Comment by m0ngr31** [comment]
I'm going to close this for now and chalk it up to Tivimate not updating the framerate
