### ISSUE TITLE
[Enhancement] Off Air for EPG

### ISSUE THREAD

**Issue by GameEnder** [tonywagner/EPlusTV#40]
Would it be possible to add a option to have the EPG to show Off Air or something to show that the ESPN+ channel is empty instead of the guide just being empty?

**Comment by m0ngr31** [comment]
I'm not sure the XMLTV spec allows that, but I'll investigate it

**Comment by 3v3rm4rt3lL** [comment]
> 

Hello, i woudn't like to create a new issue topic, just want to ask, will this app support peacock streaming service in future? Thanks.

**Comment by m0ngr31** [comment]
> Hello, i woudn't like to create a new issue topic, just want to ask, will this app support peacock streaming service in future? Thanks.

Yeah, it's on my list of things to add :)

**Comment by 3v3rm4rt3lL** [comment]
> Yeah, it's on my list of things to add :)

Great! to waiting for any updates, Regards!
