### ISSUE TITLE
SOLVED: Does not show content if using starting channel number other than 1

### ISSUE THREAD

**Issue by hectormethod** [tonywagner/EPlusTV#44]
EPlusTv works in ChannelsDVR when I leave the starting channel value set to 1. I see guide data and the stream video.
However, if I try to change it to another starting channel (e.g. 7000 or 9000), I see the channels in my guide, but do not see any streams, only the "Event Starting Soon" image. 
I have tried to remove and re-add the Docker container, but still experience the same results: works when starting channel is 1, but does not work when set to another number.
Thanks for any suggestions.

**Comment by SoSJames** [comment]
Just a suggestion, you should look at the EPlusTV Docker's log output and see what it's reporting when you try to play the channel. It should give you some clue as to what's going wrong. If not, posting the log here will make it much easier for the developer/others to help.

**Comment by hectormethod** [comment]
Output from logs:
```log
groupmod: GID '100' already exists

> eplustv@2.0.0-beta14 start
> ts-node index.ts

=== EPlusTV v2.0.0-beta14 starting... ===
Refreshing device token
Refreshing device refresh token
Refreshing BAM access token
=== Getting events ===
Looking for live events...
Looking for upcoming events...
=== Done getting events ===
=== Building the schedule ===
=== Done building the schedule ===
=== Starting Server ===
Server started on port 8000
```

**Comment by SoSJames** [comment]
OK, that indicates the server started and is listening. But what does it say when you try and play a channel in your "broken" scenario? Is it throwing an error or indicating that it's playing?

And - to clarify: Are you changing the channel numbers in Channels or via the variable when you start the EPlusTV Docker?

**Comment by m0ngr31** [comment]
I think this is a bug. I've seen people talk about it on the channels forum too. I'll take a look at it after I fix the slate bug

**Comment by SoSJames** [comment]
OK, Dev knows best!

**Comment by m0ngr31** [comment]
> OK, Dev knows best!

For me, rarely!

**Comment by m0ngr31** [comment]
I played around with this a little bit tonight and I couldn't replicate it. It worked fine with whatever channel I assigned it to.

**Comment by hectormethod** [comment]
Thanks for trying to replicate it. I am still having the issue. 
I tried again to start from scratch. Removed docker container. Reinstalled and set starting channel to 7000. 
Here are my docker settings in Unraid:
![scrx 2023-01-11-09-35 Firefox](https://user-images.githubusercontent.com/1509916/211848519-818e0e57-2046-4e89-b500-5c3fd767f362.png)

I see no data in EPG guide, and no streaming videos when opening a channel. Logs show:
```
groupmod: GID '100' already exists

> eplustv@2.0.0 start
> ts-node index.ts

=== EPlusTV v2.0.0 starting ===
Refreshing auth token
Refreshing device token
Refreshing device refresh token
Refreshing BAM access token
=== Getting events ===
Looking for live events...
Looking for upcoming events...
=== Done getting events ===
=== Building the schedule ===
=== Done building the schedule ===
=== Starting Server ===
Server started on port 8000
adduser: user 'abc' in use
```

If I change the starting channel to 1 (by leaving the starting channel value blank), then I do see streaming video:

![scrx 2023-01-11-09-32 Firefox](https://user-images.githubusercontent.com/1509916/211849013-7482be9a-8fd0-416f-8bc3-b6cf724626d2.png)

So I can use it with starting channel at 1, but then all the EPlus channels are interspersed among all the other cable channels instead of being in their own separate block of channels (e.g. 7000s, 8000s, etc.).

Thanks for any suggestions.

**Comment by SoSJames** [comment]
Not sure if it's a viable workaround, but can you try leaving the start channel section in the Unraid Docker panel blank, and instead add the START_CHANNEL="7000" variable in Unraid Docker's extra parameters section? Perhaps it'll pick it up that way.

**Comment by hectormethod** [comment]
Good thought @SoSJames, but I tried that troubleshooting step, and it did not seem to fix it.
It's a strange bug. If docker is started with `START_CHANNEL=''` parameter, I get streaming video (with channels starting at 1). But, then for some reason, having the parameter be `START_CHANNEL='8000'` in the docker start command, I get no streaming video from channels. 
It's still good with channels in the 1-100 range, just not ideal. Maybe a future update will address it. 
Thanks for the project.

**Comment by SoSJames** [comment]
Hmm. Quick question. When you set the start channel to 8000 (or wherever you want it), have you looked at the resulting channels.m3u and XMLTV file to see if EPlusTV's putting the channel numbers in as expected?

Of course, if you'd prefer to leave it be in hopes of a future update, feel free to ignore the above. And yes, thanks again to @m0ngr31 for creating such a useful project.

**Comment by dozer1dave** [comment]
> Good thought @SoSJames, but I tried that troubleshooting step, and it did not seem to fix it. It's a strange bug. If docker is started with `START_CHANNEL=''` parameter, I get streaming video (with channels starting at 1). But, then for some reason, having the parameter be `START_CHANNEL='8000'` in the docker start command, I get no streaming video from channels. It's still good with channels in the 1-100 range, just not ideal. Maybe a future update will address it. Thanks for the project.

@hectormethod Just another thought, I have resorted to deleting the contents of the /app/config folder to force a clean restart to get things working.  You'll need to re-authenticate but worth a try.

**Comment by hectormethod** [comment]
Thanks @dozer1dave, that recommendation worked! I deleted the contents of `/app/config/` folder and restarted the docker container. This triggered a re-authentication in the browser with the activation code. Now my channels start at 7000 with streaming video working.
