### ISSUE TITLE
Watchtower updates failing

### ISSUE THREAD

**Issue by ehosch** [tonywagner/EPlusTV#46]
Could not do a head request for "m0ngr31/eplustv:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"

Same as this thread... https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053

**Comment by m0ngr31** [comment]
It looks like this might be fixed now? https://github.com/containrrr/watchtower/pull/1533
