### ISSUE TITLE
Port conflict

### ISSUE THREAD

**Issue by Nemesis1433** [tonywagner/EPlusTV#47]
Is it possible to change the listening port?  Getting a conflict error in Portainer

Error: listen EADDRINUSE: address already in use :::8000

**Comment by 3v3rm4rt3lL** [comment]
May this help: just change the first port that is the port host. Example : docker run -p 8092:8000

**Comment by Nemesis1433** [comment]
No luck.  Using Portainer and used custom command and changed as you suggested.  Still starts up and says 8000 already in use.

**Comment by Nemesis1433** [comment]
Anyone have any other thoughts?  8092:8000 still produces the same error in the logs on the container.  port 8000 is already in use.

**Comment by 3v3rm4rt3lL** [comment]
Every docker container has a insolate ip and ports, when you create a docker container with eplustv this create his own virtual ip and ports 8000, when u used 8092:8000 are telling that docker port 8000 use the port 8092 on host ip. Unless you are using the container eplustv behind other docker that is conflictic with the same 8000 ports. That is you main issue. 
![1675117210289](https://user-images.githubusercontent.com/88483302/215608844-4391c793-c075-4c9a-a54f-e9248adb4d63.jpg)

**Comment by Nemesis1433** [comment]
Yep pretty much the issue.  Portainer is on 8000.  Only way I see of doing this is re-deploying Portainer and setting the agent port to 8001.  Thanks for the help!

**Comment by jefferson136** [comment]
Same issue as others above. I have tried changing the host port for EplusTV, but it doesn't work. I also tried changing Portainer's host port for TCP connections (the one that uses 8000) to something else, but this container is still not happy. Any chance of making the port configurable?

**Comment by m0ngr31** [comment]
Are you using host or bridged mode networking?

**Comment by Nemesis1433** [comment]
I got it all working.  I set up a separate network (macvlan) for this and
it's all good now.  Thank you for following up!!

**Comment by jefferson136** [comment]
> Are you using host or bridged mode networking?

I have a custom docker network setup running in bridge mode. That way I can communicate with my different containers using their container name for a hostname. Additionally, I have EPlusTV running thru a VPN container, but I had first set it up without that and still had the same issue. Any thoughts? Thanks!

**Comment by Nemesis1433** [comment]
You need to put the VPN container and EPlusTV on a separate mac vlan.  I
set up a vlan on my home switch and then created the mac vlan using that
and attached the containers to that vlan, now no issues.

**Comment by m0ngr31** [comment]
I'm going to close this
