### ISSUE TITLE
[Feature Request] Bally Sports integration

### ISSUE THREAD

**Issue by goldenpipes** [tonywagner/EPlusTV#48]
Would it be possible to integrate bally sports streams into this?

Thanks!

**Comment by m0ngr31** [comment]
It's on the roadmap, but aren't they declaring bankruptcy?

**Comment by goldenpipes** [comment]
I think certain subsidiaries are, but i would imagine, it will take years to dismantle/transfer ownership of the systems

**Comment by rh535** [comment]
This would be great!

**Comment by dcd** [comment]
@m0ngr31 I have a bally subscription and capability to sniff/etc, is there anything I can do to help get this implemented?

**Comment by m0ngr31** [comment]
I looked at adding in Bally Sports, but it's using DRM on all their live streams, so it's not possible at this time :disappointed:

**Comment by goldenpipes** [comment]
> I looked at adding in Bally Sports, but it's using DRM on all their live streams, so it's not possible at this time 😞

even if we're using our credentials from TV provider? i think its using the Adobe drm thing? is this not the same as how it works for ESPN and the like?
