### ISSUE TITLE
Getting a failed to parse stream

### ISSUE THREAD

**Issue by ssimpson89** [tonywagner/EPlusTV#5]
Running in docker on linux. I get the following when trying to launch a stream

There is an active event. Going to start the stream.
Getting stream for event:  ca34ba2a-8324-479c-9df5-e67e500639bb
Failed to parse the stream

Any thoughts? I put the container in privileged mode just in case and am still seeing it. Any thoughts?

**Comment by m0ngr31** [comment]
This can happen from a few different things...

I've experienced it from the username/password combo being bad, the event being blacked out, or if it hasn't started/has already ended.

If it is happening on every channel, it's probably your login. If your password has special characters in it, try escaping them when you are passing it to your container.

**Comment by ssimpson89** [comment]
Yeah, I noticed in the login png that docker compose passed the quotes into username. I changed that and reset my password to something simpler. I was still getting the error but I think it could have been a patience thing as well as in one case it started playing. Ill try to do some more testing. I was seeing a different result running docker run as opposed to docker compose so Ill see what I can find. Thanks for the help and this tool!

**Comment by dschaper** [comment]
I've noticed that the environment inside the container is correct, but ESPN is sending one time pass codes to the email registered for the account as a protection. I'm not sure if that can be countered, eventually things did start to stream and I got a login notification email from ESPN.

**Comment by m0ngr31** [comment]
That's interesting... I only saw that before I got the login stuff refactored and it wasn't pushing the right buttons. I'm glad it's working for you now though. Not really a way to get around that.

**Comment by hazdo** [comment]
hi @m0ngr31 Failed to parse the stream i am getting this problem even followed the detail you suggested.
is it still working.
@ssimpson89 how did you managed to reslove this problem and is it still working.

**Comment by m0ngr31** [comment]
I changed the way getting the stream works, so we can open this up again if I get more feedback.

Just for clarification for those coming in later, you should normally only get a "Failed to parse stream" message when:

* You are region blocked from something
* Event hasn't started
* Event has already ended

I'm hoping everything else works
