### ISSUE TITLE
Port 8000 Conflicts with Portainer and I can't seem to get it running on a different port

### ISSUE THREAD

**Issue by Nostradamus1973** [tonywagner/EPlusTV#52]
Good morning Everyone,

I'm new to using Docker, and as much as I love its' ease of use I'm having trouble with a few things. I guess port 8000 is also used for Portainer, so, I tried to use the following command:
docker run -p 8010:8010 -v config_dir:/app/config m0ngr31/eplustv
Everything installs fine, but, whenever I go to localhost:8010/channels.m3u I get Nothing.
I'm sure that I'm doing something wrong, however I can't seem to discern what it is.
Has anyone seen this before? I know Portainer is somewhat popular, so, I'm hoping someone has encountered this before.

Can someone please help me with my situation?

Thank you and have a nice day.

**Comment by SoSJames** [comment]
Perhaps try:
docker run -p 8010:8000 -v config_dir:/app/config m0ngr31/eplustv

That should map the port inside the container - 8000, to an external listening port of 8010. That should sidestep the port issue.

**Comment by Random214** [comment]
I am currently experiencing the same issue. 
Fresh install Ubuntu 20.04
I install **Docker**, then install from **Docker Hub**. 
I login in and says **Authentication was successful.**
Then says _opening server on http://ip: :8000 port_; 
I go to the port that it mentions on my webbrowsers and on phone even to test.

I enter url: **https://ip:8000/channels.m3u**

ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: "http://ip:8000/channels.m3u"
Access Denied.
Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.
Your cache administrator is webmaster.

**Comment by SoSJames** [comment]
@Random214 , that's not the same issue as OP. They're trying to run the docker container on a different port than its pre-configured listening port. If your docker install uses port 8000 as its default listening port, your container would error out on startup. Sounds like yours isn't doing that. Are you by any chance running your web browser through a proxy server? If so, that could be the source of your error.

**Comment by m0ngr31** [comment]
@Nostradamus1973 did @SoSJames suggestion work for you?
