### ISSUE TITLE
error: ERROR The requested URL could not be retrieved 

### ISSUE THREAD

**Issue by Random214** [tonywagner/EPlusTV#54]
Fresh install Ubuntu 20.04
Install Docker, install; Docker Hub.
Login to site with authorization code and says Authentication was successful.
Then says opening server on http://ip/: :8000 port;
I go to the port that it mentions on my webbrowsers and on phone even to test.

I enter url: https://ip:8000/channels.m3u

ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: "http://ip:8000/channels.m3u"
Access Denied.
Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.
Your cache administrator is webmaster.

**Comment by m0ngr31** [comment]
How are you running the command for the container?

**Comment by m0ngr31** [comment]
Please re-open if this is a problem still
