### ISSUE TITLE
unable to refresh BAM token

### ISSUE THREAD

**Issue by tandr3ws** [tonywagner/EPlusTV#55]
having an issue with ESPN+ only. seems to be unable to get token. 

here is a pastebin with relevant logs. https://pastebin.com/JX3U1Aay

**Comment by m0ngr31** [comment]
Are you using a VPN?

**Comment by tandr3ws** [comment]
> Are you using a VPN?

no, I am on the same network locally. were you able to view logs? can I provide any additional info? Appreciate this by the way.

**Comment by m0ngr31** [comment]
Try deleting the `tokens.json` file in your config folder and restarting the container.

**Comment by tandr3ws** [comment]
ill give it a shot... but I have tried that once or twice already. could dns have anything to do with it?

**Comment by tandr3ws** [comment]
so here's an update. I got it to work locally, mostly now. But my use case is to use it on my cloud vps that has channels dvr server installed to watch when I am out and about (my isp has terrible upload speed). no matter what it won't play ESPN+ streams and for that matter when trying to use TVE on channels, it tries to authorized any Disney owned channels like abc, ESPN, etc and gives an error message that it thinks I am out of the country... is it possible my VPS provider is blacklisted?

**Comment by m0ngr31** [comment]
Yeah there is a pretty good chance that they have blocked large swathes of VPS IP ranges

**Comment by m0ngr31** [comment]
I'm going to close this since it appears that your VPS is being IP blocked by ESPN
