### ISSUE TITLE
Request: Apple TV (MLS)

### ISSUE THREAD

**Issue by rh535** [tonywagner/EPlusTV#57]
Thank you for all your work. If possible - adding Apple TV MLS channels would be great!

Thanks!

**Comment by m0ngr31** [comment]
There is a couple of issues with adding MLS Season pass...

* Apple 2FA messes up the login flow, so it's not as simple as the others
* They use DRM on all of their streams, which prevents clients from using the playback. I'm trying to come up with a solution to this, but it's not trivial.

I will reopen this if anything changes

**Comment by rh535** [comment]
Thank you for looking into it and keeping it in mind!
