### ISSUE TITLE
Request: force MLB bitrate

### ISSUE THREAD

**Issue by dcd** [tonywagner/EPlusTV#58]
Hi, I am using one instance of this container to stream MLB only.  It works fine.

This is a gigabit fiber circuit where 720p60 is selected automatically every time by the official MLB apps.
Network between EPlusTV and the consumer (xteve) is at worst 10 gig.

When using EPlusTV, I have noticed that the stream is sometimes 480p and sometimes 720p30.  It is not being transcoded; this is what EPlusTV is feeding up.  I have env MAX_RESOLUTION = "UHD/HDR" (even though there is no UHD or HDR content on MLB)

I am not sure how the MLB bitrate gets determined by EPlusTV, but I have seen a different implementation that allows setting these values:

5600 (720p @ 60 fps)
3500 (720p)
2500 (540p)
1800 (504p)
1200 (360p)
800 (288p)
514 (216p)
192 (180p)

I would like to achieve 720p60 using EPlusTV.  Maybe this can this be done by:
- mapping the existing MAX_RESOLUTION setting to force 5600/720p60 ?
- some new env to specify bitrate for MLB ?
- whatever auto-mechanism that exists today tweaked ?

Thanks for your work and any help you can provide here.

**Comment by m0ngr31** [comment]
So the `MAX_RESOLUTION` was being used a little bit more than it is now, but things changed a bit now, and it's just used to control whether you can get 4K from FOX now.

I'm not super familiar with xteve, but whatever your client will grab the full manifest and auto-negotiate from that what quality to play. Like if you use VLC or something straight from E+, you can see it switch resolutions sometimes up front.

**Comment by dcd** [comment]
Ah, thanks for the clarification. I'll try and walk the whole chain and see what gets recieved at the ultimate consumer and go from there.
