### ISSUE TITLE
ESPN+ events creep into the linear TV slots on the guide

### ISSUE THREAD

**Issue by lionsnob** [tonywagner/EPlusTV#59]
Start command:
sudo docker run -e ESPN3=true -e SECPLUS=true -e FOXSPORTS=true -e ESPN=true -e ESPN2=true -ESPNU=true -e SEC=true -e ACCN=true -e ACCNX=true -e MLBTV=true -e MLBTV_USER='email@gmail.com' -e MLBTV_PASS='password' -e MLBTV_ONLY_FREE=true -e USE_LINEAR=true -e NUM_OF_CHANNELS=300 -p 8000:8000 -v /home/steve/eplustv/:/app/config m0ngr31/eplustv

See attached for pic and xmltv.xml file.

As title says, ESPN+ events make their way into the first ten or so channels that overlap with linear TV.
[xmltv.zip](https://github.com/m0ngr31/EPlusTV/files/11312953/xmltv.zip)
![Capture](https://user-images.githubusercontent.com/54520364/234069067-d5c96ee7-fabf-4168-a7f4-4233205e8c0b.PNG)

**Comment by m0ngr31** [comment]
Good find, I think this happens after initial scheduling. I'll see what I can figure out

**Comment by m0ngr31** [comment]
This should be fixed now :crossed_fingers:
