### ISSUE TITLE
MLB free games do not show in the guide

### ISSUE THREAD

**Issue by lionsnob** [tonywagner/EPlusTV#60]
Command:
sudo docker run -e ESPN3=true -e SECPLUS=true -e FOXSPORTS=true -e ESPN=true -e ESPN2=true -ESPNU=true -e SEC=true -e ACCN=true -e ACCNX=true -e MLBTV=true -e MLBTV_USER='email@gmail.com' -e MLBTV_PASS='password' -e MLBTV_ONLY_FREE=true -e USE_LINEAR=true -e NUM_OF_CHANNELS=300 -p 8000:8000 -v /home/steve/eplustv/:/app/config m0ngr31/eplustv

As the title says, MLB free games do not show in the guide. XMLTV.xml file attached.
[xmltv.zip](https://github.com/m0ngr31/EPlusTV/files/11312971/xmltv.zip)

Thanks for this great tool!

**Comment by m0ngr31** [comment]
I found the issue on this one, a fix will be released on the next update
