### ISSUE TITLE
[Feature Request] The Tennis Channel

### ISSUE THREAD

**Issue by jefferson136** [tonywagner/EPlusTV#62]
Hello, I have been playing with and using EPlusTV for a little bit now and it's great! Awesome work! I use both the ESPN and Fox Sports integrations, then feed everything into Xteve and Plex, but wanted to request adding support for **The Tennis Channel**. 

Currently, they offer a TVE stream at [tennischannel.com/watchnow](tennischannel.com/watchnow) after authenticating with your TV provider, which I have, but would love to get it into the lineup with my other sports channels. Based on some testing, I do _not_ think they encrypt their streams, as I have at times been able to find .m3u8 streams via Chrome's console and play them back using VLC, but of course I could be wrong. Also, to clarify, I am not asking for integration with their standalone service "TennisTV", just accessing the main channel "The Tennis Channel" that I have thru my DIRECTV STREAM account and can access at the URL above. I would be happy to provide access to my account if needed for development. 

Let me know if you think this might be possible. Again, great work on this project! Thanks so much!

**Comment by chasut** [comment]
+1 on this and Tennis Channel Plus

**Comment by m0ngr31** [comment]
TVE is a little outside of the scope of what I'm building.. you'd be better off using the TVE functionality built into Channels DVR since that'd work out of the box. I'm open to adding in support for Tennis Channel Plus if I had credentials though.

**Comment by desairs** [comment]
> TVE is a little outside of the scope of what I'm building.. you'd be better off using the TVE functionality built into Channels DVR since that'd work out of the box. I'm open to adding in support for Tennis Channel Plus if I had credentials though.

I would be super appreciative if you could add tennis channel plus.  I can give you my credentials if you are open to it.

**Comment by m0ngr31** [comment]
I just spent some time playing with this. It's kinda lame, they don't have an Android TV app, so I can't reverse engineer how it works :disappointed:
