### ISSUE TITLE
[Feature Request] Adding DAZN as a provider (similar to ESPN+)

### ISSUE THREAD

**Issue by bbruenings** [tonywagner/EPlusTV#66]
Hi and thank you for the great work so far, I really enjoy using EPlusTV with Channels.

I was wondering if adding DAZN is a possibility, it is really common in Germany as it broadcasts Bundesliga / Champions League and the NFL (all games starting next year). 

I would be happy to help with the implementation if you can give me a little starting point. 

Thanks in advance for looking into it!

**Comment by m0ngr31** [comment]
Yeah, that'd be great to be able to add in DAZN. I'm not sure if they use DRM, but it's worth a shot to look at. I'm happy to accept a PR if you want to work on it

**Comment by joejoe402012** [comment]
Yea they use DRM

**Comment by m0ngr31** [comment]
I figured as much. The people in my network that I know work there are pretty sharp
