### ISSUE TITLE
how can i run this script via Socks5 Proxy

### ISSUE THREAD

**Issue by waqarr** [tonywagner/EPlusTV#67]
Dear Respected Sir/Developer, 
                     how can i run this script via Socks5 Proxy or use socks5 proxy inside script. i tried on different USA vps it not work. ESPN+ detect datacenter ip. 

Thank you so much
Best Regards,
Waqar

**Comment by m0ngr31** [comment]
Unfortunately bypassing the region blocking with a proxy or VPN will get my project shut down faster than anything else, so I can't help with that
