### ISSUE TITLE
Channel names not displaying properly

### ISSUE THREAD

**Issue by burntoc** [tonywagner/EPlusTV#69]
I'm running the container on Unraid.  I have false for ESPN+ as I don't use it, and I set true for 8 ESPN and FOX channels I have.  

I saw the prompts in the logs to authenticate with ESPN and FOX and that went well.  I have Channels pulling the m3u and xmltv file, but every channel shows as EPlusTV # and there is no guide info or logos.

Here is my M3U

`#EXTM3U
#EXTINF:0 tvg-id="1.eplustv" channel-number="1" tvg-chno="1" tvg-name="EPlusTV 1" group-title="EPlusTV", EPlusTV 1
http://192.168.1.122:8000/channels/1.m3u8

#EXTINF:0 tvg-id="2.eplustv" channel-number="2" tvg-chno="2" tvg-name="EPlusTV 2" group-title="EPlusTV", EPlusTV 2
http://192.168.1.122:8000/channels/2.m3u8

#EXTINF:0 tvg-id="3.eplustv" channel-number="3" tvg-chno="3" tvg-name="EPlusTV 3" group-title="EPlusTV", EPlusTV 3
http://192.168.1.122:8000/channels/3.m3u8

#EXTINF:0 tvg-id="4.eplustv" channel-number="4" tvg-chno="4" tvg-name="EPlusTV 4" group-title="EPlusTV", EPlusTV 4
http://192.168.1.122:8000/channels/4.m3u8

#EXTINF:0 tvg-id="5.eplustv" channel-number="5" tvg-chno="5" tvg-name="EPlusTV 5" group-title="EPlusTV", EPlusTV 5
http://192.168.1.122:8000/channels/5.m3u8

#EXTINF:0 tvg-id="6.eplustv" channel-number="6" tvg-chno="6" tvg-name="EPlusTV 6" group-title="EPlusTV", EPlusTV 6
http://192.168.1.122:8000/channels/6.m3u8

#EXTINF:0 tvg-id="7.eplustv" channel-number="7" tvg-chno="7" tvg-name="EPlusTV 7" group-title="EPlusTV", EPlusTV 7
http://192.168.1.122:8000/channels/7.m3u8

#EXTINF:0 tvg-id="8.eplustv" channel-number="8" tvg-chno="8" tvg-name="EPlusTV 8" group-title="EPlusTV", EPlusTV 8
http://192.168.1.122:8000/channels/8.m3u8

#EXTINF:0 tvg-id="9.eplustv" channel-number="9" tvg-chno="9" tvg-name="EPlusTV 9" group-title="EPlusTV", EPlusTV 9
http://192.168.1.122:8000/channels/9.m3u8`

I can click on a channel in Channels and watch it, but I'm trying to figure out why it isn't populating the channel names in the m3u ang EPG.

**Comment by m0ngr31** [comment]
The channels don't display as linear (use TVE in Channels if you want that). They are assigned to a channel as close as they can get to each other. `EPlusTV #` is the proper channel name. The EPG not showing up is a different issue. I'm guessing you're giving it the wrong URL for it?
