### ISSUE TITLE
[Feature Request] Include the event type in the xml title property

### ISSUE THREAD

**Issue by bweezy21** [tonywagner/EPlusTV#70]
It would be great to include the event type in the xml guide title property for quickly seeing if what is playing is football, basketball, volleyball, etc. Other apps traditionally place the event type as the title property and the teams as the subtitle property.

**Comment by m0ngr31** [comment]
I'll work on adding this. Titles just get really long, but it'd be good to have

**Comment by m0ngr31** [comment]
This is now in [v2.0.18](https://github.com/m0ngr31/EPlusTV/releases/tag/v2.0.18)
