### ISSUE TITLE
Expected behavior question

### ISSUE THREAD

**Issue by SoSJames** [tonywagner/EPlusTV#73]
Quick question. I'm noticing that EPlusTV looks like it's passing the equivalent of each stream's master (adaptive bitrate) m3u8 for every channel now. I noticed it first because Fox Sports streams were ignoring the resolution limit and trying to play 4K in all of my players. Then, I noticed that the ESPN+ NHL feeds would play in 30fps in one player and 60fps in another. So, I opened each with FFMPEG and saw that all of the resolutions/bitrates are in the m3u8. I could select them using FFMPEG's -map flag and they all work. Is this expected behavior or did something in the code or with the streamers change? No hurry, since this isn't the end of the world. Just wondering.

**Comment by m0ngr31** [comment]
Yeah, that's intended. I have to do the FOX resolution stuff because it won't grab the 4K HDR/SDR manifest if you don't explicitly ask for it
