### ISSUE TITLE
TSN + Sportsnet?

### ISSUE THREAD

**Issue by rockymalubay** [tonywagner/EPlusTV#75]
Anyway y'all can add TSN and Sportsnet on here? 

This seems great and I want to try it out but unfortunately ESPN+ is not available in Canada. 

Thanks for all your hard work.

**Comment by m0ngr31** [comment]
Hard to say without access to those services. Do you know if they use TVE? Or if they are using DRM?

**Comment by dtngfan85** [comment]
Both TSN and Sportsnet have DRM protection on all of their live streams.
