### ISSUE TITLE
Channels 404 

### ISSUE THREAD

**Issue by jonbbrad** [tonywagner/EPlusTV#77]
I have ESPN setup using my TV Providers login info, I have USE_LINEAR set to True... My ESPN Channels have been mapped to EPlusTV 1-6. When I watch one of these channels I'm finding that I can't watch them like an actual TV channel; there seems to be a time between current program I'm watching, and upcoming program where the EPlusTV channel I am watching will disconnect, and if I try to reconnect I get a 404. I will continue to get a 404 until the next event becomes active. This doesn't work for live games that run long, I've also not been able to come in and watch the end of a show. When I look at the docker log I see this: 

Failed to parse the stream
Could not get a playlist for channel #4. Please make sure there is an event scheduled and you have access to it.
Channel #4 has an active event (Miami (OH) vs. Toledo (Championship)). Going to start the stream.
Event status:  UPCOMING
Error: No streaming data available
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:498:15)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Could not get stream data. Event might be upcoming, ended, or in blackout...

If I'm watching ESPN2 as a Linear Channel isn't there a way to just load the feed and let it play?

**Comment by m0ngr31** [comment]
With the recent changes I made to making events last longer, I'd nuke your entries and schedule databases and remove the USE_LINEAR option. I'll be removing that flag entirely in the next update.

**Comment by jonbbrad** [comment]
I'll give that a try, thank you.

**Comment by m0ngr31** [comment]
I'm going to close this. New version is launching later today without linear channels support
