### ISSUE TITLE
/ in description will break import

### ISSUE THREAD

**Issue by Wnt2Fly** [tonywagner/EPlusTV#81]
Couldn't figure out why my guide wouldn't import beyond channel 30 tonight. turns out 31 had the following:

`<programme channel="31.eplustv" start="20231209173000 +0000" stop="20231210023000 +0000">
<title lang="en">England tour of West Indies 2023/24 - West Indies vs. England (3rd ODI)</title>
<desc lang="en">England tour of West Indies 2023/24 - West Indies vs. England (3rd ODI)</desc>
<icon src="https://artwork.api.espn.com/artwork/collections/airings/67d9693f-a83c-490e-84d0-99b0407d2465/default?width=640&apikey=1ngjw23osgcis1i1vbj96lmfqs&timestamp=202312060023"/>
<live/>]
`

I'm suspect the / in the title and desc will need to be escaped in order to import correctly. ProgDVB and Plex/xteve failed to bring in any EPG data beyond 30.

thanks

**Comment by m0ngr31** [comment]
I'm not sure what would cause this. As far as I know, I shouldn't have to escape `/`: https://en.wikipedia.org/wiki/XML#Escaping

Could it be a different event title is breaking it?

**Comment by m0ngr31** [comment]
Closing stale ticket
