### ISSUE TITLE
Renaming Dedicated Linear Channels

### ISSUE THREAD

**Issue by desairs** [tonywagner/EPlusTV#82]
Would it be possible to rename channels to the actual names when using Dedicated Linear Channels?: true?

Example is EplusTV 7001 7001 is current displayed.  I'd like it to be ACCN 7001 7001.

If it messes up a configuration or is too much work no big deal.

Thanks in advance!

**Comment by m0ngr31** [comment]
I'm actually getting rid of the linear option in the next update. It casues too many issues

**Comment by m0ngr31** [comment]
I re-did the linear channel stuff. It should do what you want now - just look at the readme
