### ISSUE TITLE
Adding ESPN artwork for Channels?

### ISSUE THREAD

**Issue by rh535** [tonywagner/EPlusTV#84]
I was wondering if it would be possible to integrate the ESPN channel artwork into the channels. I think for people watching on a big tv it would be a nice enhancement to the guide's look.

Example Event Logo: [(https://artwork.api.espn.com/artwork/collections/airings/0df86b3c-7776-4cc5-b373-a88e754d4f28/default?width=640&apikey=1ngjw23osgcis1i1vbj96lmfqs&timestamp=202311072057)](https://artwork.api.espn.com/artwork/collections/airings/0df86b3c-7776-4cc5-b373-a88e754d4f28/default?width=640&apikey=1ngjw23osgcis1i1vbj96lmfqs&timestamp=202311072057)

Example Event Title: Title of event: Basketball - Texas Tech vs. Houston

**Comment by m0ngr31** [comment]
Each event has artwork already. I can't do that for each channel since it will change constantly depending on when the client updates the xmltv file. Your client would never use the right one.

**Comment by rh535** [comment]
Sorry - Wrong title/photo

Correct Title for Example: Basketball - Middle Tennessee vs. Grand Canyon

Correct URL for Example: [(https://artwork.api.espn.com/artwork/collections/media/a9c6f3a9-7b83-4cb2-90f6-9fa294f36617/default?width=640&apikey=1ngjw23osgcis1i1vbj96lmfqs&timestamp=202312212048)](https://artwork.api.espn.com/artwork/collections/media/a9c6f3a9-7b83-4cb2-90f6-9fa294f36617/default?width=640&apikey=1ngjw23osgcis1i1vbj96lmfqs&timestamp=202312212048)

**Comment by m0ngr31** [comment]
Have you seen more instances of this? I've only seen it happen when there is a caching issue with old data in xTeve or Channels.

**Comment by m0ngr31** [comment]
Closing stale ticket
