### ISSUE TITLE
MSG+ Pregame

### ISSUE THREAD

**Issue by adamef93** [tonywagner/EPlusTV#87]
Me again haha

Totally not a huge deal, but could MSG+ events be set to start 30 minutes early? There's a pregame show for each of the teams (hockey at least, idk about basketball) that doesn't come through through when watching through E+.

Thanks in advance!

**Comment by m0ngr31** [comment]
Yeah that's easy enough. I'll try and add it in tonight.

Just curious, how has the token refresh stuff worked out? Does you have to constantly login?

**Comment by adamef93** [comment]
I haven't needed to authenticate with MSG+ since I first added it to E+, which is saying a lot considering the web UI and phone app make me sign back in from scratch fairly often. Nicely done 😎

**Comment by m0ngr31** [comment]
I added this for version 2.1.5. Should be on Docker Hub in a few minutes

**Comment by adamef93** [comment]
Thanks! Just wondering, any particular reason it shows up as a different channel instead of preceding the game on the same channel?

**Comment by m0ngr31** [comment]
Ahh, that's a good point. I'll have to think about that. Maybe instead of including the pre-event show I'll just make the start schedule 30 minutes earlier like you suggested...

**Comment by m0ngr31** [comment]
Made that change last night, let me know if that's better or not

**Comment by adamef93** [comment]
Looks like the pregame is still on a different channel

**Comment by m0ngr31** [comment]
The existing ones will continue to exist for few more days because they were already in the schedule. The new version doesn't have a specific "pregame" event anymore, just padding the start by 30 minutes
