### ISSUE TITLE
Paramount+

### ISSUE THREAD

**Issue by iosdave** [tonywagner/EPlusTV#88]
How do i setup Paramount+? 

I used the following Variable PARAMOUNTPLUS and set it to true, but I don't get prompted to login. 

Im using unraid for what its worth.

**Comment by iosdave** [comment]
disregard, i removed an re-added the variable and it works now.  

Is it possible to add the non sports linear channels?

**Comment by m0ngr31** [comment]
> Is it possible to add the non sports linear channels?

It's possible, but it's outside the scope of what I'm trying to do here. If someone wants to fork my project and just use the P+ logic it shouldn't be too bad
