### ISSUE TITLE
[Request] Add back the USE_LINEAR env variable

### ISSUE THREAD

**Issue by jefferson136** [tonywagner/EPlusTV#89]
So I started having issues with missing channels and them being mixed up. When I finally had time to investigate and realized the `USE_LINEAR` environment variable was removed from the image, which I use and I believe is essential for my workflow. I was hoping that option can be added back to the `master` branch, so I can use new features too. 

If I missing a way to modify my workflow without this option, please let know. I'm open to changing it, but so far it works for me. In the meantime, I am pulling an older tag, where that variable is working and my setup is back to working perfectly. Maybe an option is keeping and applying the variable only to ESPN (with cable login), since those are fixed channels vs ESPN+ (where it's event based). 

**My workflow**: EPlusTV (m3u and xml) -> xTeve (where I have multiple feeds and xmls, all mapped into a single channel lineup and guide) -> Plex & Jellyfin (which just has one feed and one XML to manage). 

Thanks for reading and the EPlusTV project, it really is great!

**Comment by m0ngr31** [comment]
The `USE_LINEAR` stuff was a headache so it wasn't worth it for me to keep maintaining it ATM. I don't understand your workflow though so I can't say for sure what the workaround is for you

**Comment by jefferson136** [comment]
Thanks for the reply. Basically, because I have multiple sources of content (not just from EPlusTV), I aggregate all the sources (.m3u) and their individual guide data (xml) using xTeve. This allows me to create a singular channel lineup with guide data (with content from all sources), enable some buffering and other options, and have only one feed into the server (mainly Plex). Inside of xTeve, you can map a channel from a playlist to a channel from an XML source. These are fixed and if they change (like in the new version of EPlusTV), then I have to manually remap the channels. xTeve does allow for a cron schedule to update each playlist and xml info, which I use, but that would only allow if I had say all the ESPN+ feeds in a set range since they share same channel name and metadata (i.e. ESPN+, logo, category). This wouldn't work for static channels (i.e. ESPN, ESPN2, SEC Network), which have dedicated names, logos, etc. 

One thing I can potentially do is run two instances of EPlusTV, one running the `latest` tag to get all the ESPN+ feeds and other dynamic feeds and one running `v2.0.22` for just the static linear channels (ESPN, ESPN2, SEC Network, etc). Put both feeds into xTeve and keep them in different channel number ranges.

**Comment by m0ngr31** [comment]
I've re-implemented the linear channel stuff, it works a bit different that before, but you can see if it'll work for you now.

**Comment by jefferson136** [comment]
Thanks for follow up @m0ngr31! I finally got a chance to redo my integration with this and I'm up and working mostly how I want on the `latest` tag and using the new `LINEAR_CHANNELS` variable where available. So while I understand dynamic sources (like ESPN+) can't have a dedicated channel to them, would it be possible to at least group them by provider? For example, all ESPN+ would be say channels 100-199, Fox Sports 200-215, Paramount+ 300-310, MLB.TV 400-461, etc. This way I could create my channel lineup in xTeve/Threadfin in a mostly known order and assign channel logo artwork to these groups (i.e. ESPN+ logo for all ESPN+ channels). Right now they are all mixed up and it can be a pain to manage. Hope this make sense and once again thanks for the awesome app!

**Comment by m0ngr31** [comment]
What might be easier in the meantime is if you ran different containers for ESPN+, MLB, FOX and then limit them by `NUM_OF_CHANNELS`?

**Comment by jefferson136** [comment]
Yup that is exactly my plan, which is easy enough to do. I just wasn't sure if adding that capability was something you would consider.
