### ISSUE TITLE
how can i run the script with 

### ISSUE THREAD

**Issue by waqarr** [tonywagner/EPlusTV#96]
i install the script directly without docker

how can i provide the environment variable inside command

```npm start```

i want to enable ```PROXY_SEGMENTS``` increase channels ```NUM_OF_CHANNELS``` and change port how can i do this in command line

**Comment by m0ngr31** [comment]
You just run it before `npm start`: `PROXY_SEGMENTS=true NUM_OF_CHANNELS=5000 npm start`
